<?php
/**
 * Decode Timestamp from QR Code
 * 
 * This script decodes the encryptedTimestamp generated by scanqr.js
 * Format: BASE36_TIMESTAMP-RANDOM_STRING (e.g., "LM3XY4-K7P9Q1")
 * 
 * Usage:
 * - POST request with JSON body: {"code": "LM3XY4-K7P9Q1"}
 * - GET request with query parameter: ?code=LM3XY4-K7P9Q1
 */

header('Content-Type: application/json');

// Function to extract code from WhatsApp message
function decodeMsg($whatsappMsg) {
    // Remove extra whitespace and normalize line breaks
    $msg = trim($whatsappMsg);
    
    // Pattern to match "CODE: XXXXXX-YYYYYY" format
    // Supports various line break formats and spacing
    $pattern = '/CODE:\s*([A-Z0-9]+-[A-Z0-9]+)/i';
    
    if (preg_match($pattern, $msg, $matches)) {
        return [
            'success' => true,
            'code' => strtoupper(trim($matches[1])),
            'original_message' => $msg
        ];
    }
    
    return [
        'success' => false,
        'error' => 'Could not extract code from message. Expected format: "CODE: XXXXX-XXXXX"',
        'original_message' => $msg
    ];
}

// Function to decode the encrypted timestamp
function decodeTimestamp($encryptedTimestamp) {
    // Remove any whitespace and convert to uppercase for consistency
    $code = strtoupper(trim($encryptedTimestamp));
    
    // Split by dash to separate timestamp and random string
    $parts = explode('-', $code);
    
    if (count($parts) !== 2) {
        return [
            'success' => false,
            'error' => 'Invalid code format. Expected format: TIMESTAMP-RANDOM',
            'code' => $code
        ];
    }
    
    $base36Timestamp = $parts[0];
    $randomString = $parts[1];
    
    // Convert base36 timestamp back to decimal (seconds)
    $timestampSeconds = base_convert(strtolower($base36Timestamp), 36, 10);
    
    // Validate timestamp (should be a reasonable Unix timestamp in seconds)
    if (!is_numeric($timestampSeconds) || $timestampSeconds < 1000000000) {
        return [
            'success' => false,
            'error' => 'Invalid timestamp value',
            'code' => $code,
            'parsed_timestamp' => $timestampSeconds
        ];
    }
    
    // Calculate age of the code
    $currentTime = time();
    $ageSeconds = $currentTime - $timestampSeconds;
    
    // Convert to readable datetime
    $datetime = new DateTime("@$timestampSeconds");
    $datetime->setTimezone(new DateTimeZone('Asia/Kuala_Lumpur')); // Malaysia timezone
    
    return [
        'success' => true,
        'code' => $code,
        'timestamp_seconds' => (int)$timestampSeconds,
        'timestamp_milliseconds' => (int)$timestampSeconds * 1000,
        'datetime' => $datetime->format('Y-m-d H:i:s'),
        'datetime_iso' => $datetime->format('c'),
        'age_seconds' => $ageSeconds,
        'age_minutes' => round($ageSeconds / 60, 1),
        'random_string' => $randomString,
        'is_expired' => $ageSeconds > 180, // Consider expired after 180 seconds
        'decoded_at' => date('Y-m-d H:i:s')
    ];
}

// Get code or message from POST or GET request
$code = null;
$message = null;

if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    // Handle JSON POST request
    $input = file_get_contents('php://input');
    $data = json_decode($input, true);
    $code = $data['code'] ?? null;
    $message = $data['message'] ?? null;
} elseif ($_SERVER['REQUEST_METHOD'] === 'GET') {
    // Handle GET request
    $code = $_GET['code'] ?? null;
    $message = $_GET['message'] ?? null;
}

// If message is provided, extract code from it first
if ($message) {
    $extractResult = decodeMsg($message);
    
    if (!$extractResult['success']) {
        echo json_encode($extractResult, JSON_PRETTY_PRINT);
        exit;
    }
    
    $code = $extractResult['code'];
    
    // Decode the extracted code
    $decodeResult = decodeTimestamp($code);
    
    // Add extraction info to the result
    $decodeResult['extracted_from_message'] = true;
    $decodeResult['original_message'] = $extractResult['original_message'];
    
    echo json_encode($decodeResult, JSON_PRETTY_PRINT);
    exit;
}

// If only code is provided (backward compatibility)
if (!$code) {
    echo json_encode([
        'success' => false,
        'error' => 'No code or message provided',
        'usage' => [
            'POST_code' => 'Send JSON body with {"code": "LM3XY4-K7P9Q1"}',
            'POST_message' => 'Send JSON body with {"message": "Hey, Donkas Lab\\nPut me in the waitlist queue\\n\\nCODE: LM3XY4-K7P9Q1\\n[Please send without changes]"}',
            'GET_code' => 'Use query parameter ?code=LM3XY4-K7P9Q1',
            'GET_message' => 'Use query parameter ?message=CODE: LM3XY4-K7P9Q1'
        ]
    ], JSON_PRETTY_PRINT);
    exit;
}

// Decode and return result
$result = decodeTimestamp($code);
echo json_encode($result, JSON_PRETTY_PRINT);
